SET IDENTITY_INSERT [dbo].[Categories] ON
INSERT INTO [dbo].[Categories] ([Id], [Name]) VALUES (1, N'קטניות')
INSERT INTO [dbo].[Categories] ([Id], [Name]) VALUES (2, N'מוצרי יסוד')
INSERT INTO [dbo].[Categories] ([Id], [Name]) VALUES (3, N'קמחים')
INSERT INTO [dbo].[Categories] ([Id], [Name]) VALUES (4, N'פיצוחים')
INSERT INTO [dbo].[Categories] ([Id], [Name]) VALUES (5, N'מוצרי אפייה')
INSERT INTO [dbo].[Categories] ([Id], [Name]) VALUES (6, N'ממתקים')
INSERT INTO [dbo].[Categories] ([Id], [Name]) VALUES (7, N'תבלינים')
INSERT INTO [dbo].[Categories] ([Id], [Name]) VALUES (8, N'תבלינים בשקית')
INSERT INTO [dbo].[Categories] ([Id], [Name]) VALUES (9, N'שימורים')
INSERT INTO [dbo].[Categories] ([Id], [Name]) VALUES (10, N'שמנים ומיצים')
INSERT INTO [dbo].[Categories] ([Id], [Name]) VALUES (11, N'מוצרי טבע')
INSERT INTO [dbo].[Categories] ([Id], [Name]) VALUES (12, N'חטיפים מין הטבע')
INSERT INTO [dbo].[Categories] ([Id], [Name]) VALUES (13, N'שוקולדים של שמרלינג')
INSERT INTO [dbo].[Categories] ([Id], [Name]) VALUES (14, N'דגים')
INSERT INTO [dbo].[Categories] ([Id], [Name]) VALUES (16, N'אורז כיטוב')
INSERT INTO [dbo].[Categories] ([Id], [Name]) VALUES (17, N'אחר')
SET IDENTITY_INSERT [dbo].[Categories] OFF
